### ISSUE TITLE
Missing Navigation Image Upload Choice

### ISSUE THREAD

**Issue by Mihari** [mgsisk/inkblot#28]
For the life of me I can not find the option anymore to upload an image to replace the comic navigation buttons in the latest version of inkblot. Working as intended?

**Comment by mgsisk** [comment]
That's correct. The webcomic navbars are now widgetized, so you can just drop in a couple of **[Webcomic] Link** widgets and upload images via those. I notice this doesn't actually work within the Customizer, though; it has to be done from the Widgets page. I'm not sure there's a reliable fix for that.

**Comment by Mihari** [comment]
Well, okay so what happens when you want to replace the default top and bottom over the comic nav with images?

**Comment by mgsisk** [comment]
Adding a widget to **Webcomic Navigation Header** or **Webcomic Navigation Footer** automatically removes the default navigation links. Those links are now only shown if you *haven't* added any widgets to those areas.

**Comment by Mihari** [comment]
Ah! Nifty! Nice job!

**Comment by mgsisk** [comment]
Closing this issue; the image upload problem is actually a Webcomic issue.

**Comment by gstrout** [comment]
Mike, you said: 

> "Adding a widget to Webcomic Navigation Header or Webcomic Navigation Footer automatically removes the default navigation links. Those links are now only shown if you haven't added any widgets to those areas."

The **Webcomic Navigation Header** and **Webcomic Navigation Footer** widget areas no longer appear on my Widget screen. Was this an intentional change made in an update? 

Is there an alternate method to adjust the Navigation? 

![widget-screen-01](https://cloud.githubusercontent.com/assets/6145371/9277248/bd36635e-425d-11e5-9ba4-b2781fea8fb4.png)
