### ISSUE TITLE
Primary navigation isn't centering; transition property isn't working either

### ISSUE THREAD

**Issue by pixel-prism** [mgsisk/inkblot#69]
I've got my site at http://cvilbrandt.naiya.org and I'm trying my hardest to get the primary navigation bar to center at the top of the page!

I have given each li a custom class and replaced their text with images. At this point, I've tried so many things, my head is spinning. I'm sure it's all a tangled mess from trying to fix this, but here's the CSS I've got right now.

    #menu-primary-menu {
    	display: flex;
    	justify-content: center; /* Testing to see if flex/justify will work */
    	padding: 0; /* Seeing if there's a default padding value messing with things */
    	text-align: center; /* The usual way of centering */
    	background: #fff; /* Making sure the container is as wide as I think it is */
    	margin: auto; /* The other usual way of centering */
    }
    
    #menu-primary-menu li {
    	padding: 0;
    	display: block; /* Did block and inline-block both */
    	float: left;
    } 
    
    #menu-primary-menu li a{
    	display: inline-block;
    	transition: background 0.2 ease;
    }  

Also, the transition property isn't working either. Maybe I'm getting the CSS wrong there, though; this is the first time I've tried to use it.

Thanks in advance!

**Comment by mgsisk** [comment]
There's a `display: inline-block !important;` set for `#menu-primary-menu` in your custom CSS… probably in the customizer? Just remove that line so it looks like:
```css
#menu-primary-menu {
	text-align: center !important;
	margin: auto !important;
	width: 100%;
}
```
and the menu should center properly.

The `transition` isn't working because you're missing a unit on the transition duration; it should be `0.2s`. It probably still won't work the way you want, though, because *technically* `background-image` can't be `transition`ed (a cursory Google search suggests that some browsers might support this, but it's non-standard and the actual effect may vary by browser).

To get the effect you're probably going for requires a bit of round-about thinking… luckily, it looks like you're most of the way there already.

You have the standard link image set as the background of the containing `<li>`, which is perfect; the trick is to set the hover image as the background image of the link (always, not just on hover like it is now), and then transition the link's `opacity`, so that it's `opacity: 0;` normally (allowing the `<li>`'s background to show through), and transitions to `opacity: 1;` on hover (revealing the link's background image).

**Comment by pixel-prism** [comment]
Oh my god, thank you, haha! As expected, I just typed myself in circles so many times that I stepped on my own toes. The centering works great!! And so does the transition css; thank you so much for taking the time to walk me through it. Cheers!!
